name: Build Aria
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v1
    - name: create image
      run: |
        cp dockerfile.mingw dockerfile
        docker build -t a2w:x64 .
    - name: get aria
      run: |
        docker run -d --name cpa2w a2w:x64 /bin/bash
        docker cp cpa2w:/aria2/src/aria2c.exe .
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aria
        path: ./aria2c.exe
